宜聚网: |
    【宜聚网】年华21+ 车贷前10，之家63！媒体限量单！渠 道 3月/2.25  6月/3.70  12月/6.05
     https://shimo.im/docs/M0q3FAIpOaoddj7B 可复投，可大额，红包加息可用！4月8号更换链接 老链接可以投资和复投
#网利宝: 网利宝 3月/2.85（不议价）  YD渠道，查号复投，做错无返！
#     https://shimo.im/doc/OyicspZmmIc4ADuN?r=MPL778
清单: "每日清单 有问题私聊  \n https://shimo.im/docs/0B2KmS4IEtAPihlS"
银谷在线: |
 https://shimo.im/docs/CiAIRLxab8EildMU  【银谷在线】月标/1.30
宝象金融: |
 宝象金融https://shimo.im/doc/eDAjx514XEYOWZcs/ 「宝象金融  」5k档125/月标2.25/二月3.65
你我贷: |
 https://shimo.im/docs/SEnfX0yWgtUXKonH/ 「你我贷」三月标1.25不限额（4.4号新上）
米族金融:
 https://shimo.im/doc/yI3Veoty17Y1A6LP?r=ZJ785Qe 【米族金融】30/1.6  60天3.35 90/4.8（4.4号45天取消，其他标期限额）
宜人贷:
 【宜人贷】3月/161  6月/241  12月/2.66   4月2号新上 https://shimo.im/doc/PA45x5XsqnIjjq3H?r=N2Z13E/
万盈金融:
 【万盈金融】  4月1号之前注 册60天1.3 年标 2.0    4月1号之后注  册60天1.4  年标 3.95
 https://shimo.im/docs/D3g4DoALoY4LEJlb/
才米公社:
  才米公社  1.35/2.35/2.85
 https://shimo.im/docs/wGaw35uNzL8fNmhe/
信而富:
 信而富 纽交所上市前之家前10强平台，3月 6月标~客户年化近14！https://shimo.im/docs/tmlwU6MlxtgW5nJD  3月标1.75
信通袋:
 信通袋 代理1月0.8 3月1.88 6月3.38（1月首 投限额1-10W，3月、6月不限额，首 投 https://shimo.im/docs/CzgDMfm4IQ88ADbP
积木盒子:
 积木盒子 答 J,MHZ   1/2/3/6   0.05、0.1/0.35/0.9  https://shimo.im/doc/lgRMHuYVg30rXZQE?r
 1月标 3月标 不限量！
生菜金融:
 https://shimo.im/doc/gYOkKsOiDFkZYMmT/ 「生菜金融，季标2.25
理财范:
 https://shimo.im/docs/XBZMRnDB9tYtOqjF 理财范 1.3（4.9号换链接涨价）
人人聚财:
 人人聚财  2.0  继续上量
 https://shimo.im/docs/dICzmJjKz2QvLBD8
高搜易: |
 https://shimo.im/docs/rv4OyAoARrgMrmZ8/ 高搜易,上市系，临时补量大力推，背景不解释主推三月标，单笔不限额1.3
i财富:
 i财富 https://shimo.im/docs/jyZOW0Fb1REqevhw  i财富代理1.8
恩科e贷:
  恩科e贷15天标 0.85
  https://shimo.im/docs/emKupBOU5bwHfWKv/