宜聚网: 【宜聚网】年华21+ 车贷前10，之家63！媒体限量单！渠 道 3月/2.25  6月/3.70  12月/6.05
     https://shimo.im/docs/M0q3FAIpOaoddj7B 可复投，可大额，红包加息可用！4月8号更换链接 老链接可以投资和复投
网利宝: 网利宝 3月/2.85（不议价）  YD渠道，查号复投，做错无返！
     https://shimo.im/doc/OyicspZmmIc4ADuN?r=MPL778
清单: 每日清单 有问题私聊 https://shimo.im/docs/0B2KmS4IEtAPihlS
银谷在线: https://shimo.im/docs/CiAIRLxab8EildMU
         银谷在线】月标/1.30   4月1号降价